#!/usr/bin/env bash

set -euo pipefail

PROJECT_ROOT="$(git -C "${BATS_TEST_DIRNAME}" rev-parse --show-toplevel)"

load_core() {
  source "${PROJECT_ROOT}/vpskit/core/common.sh"
  # shellcheck disable=SC1090
  source "${PROJECT_ROOT}/vpskit/core/$1"
}

reset_vpskit_test_env() {
  unset VPSKIT_DRY_RUN
  unset VPSKIT_DRY_RUN_MUTATION_FILE
  unset VPSKIT_TEST_EUID
  unset VPSKIT_TEST_OS_ID
  unset VPSKIT_TEST_OS_VERSION_ID
  unset VPSKIT_TEST_OS_VERSION_CODENAME
  unset VPSKIT_TEST_PORT_IN_USE
  unset VPSKIT_TEST_TCP_PORT_IN_USE
  unset VPSKIT_TEST_UDP_PORT_IN_USE
  unset VPSKIT_TEST_DNS_HEALTH_RESULT
  unset VPSKIT_TEST_DNS_HEALTH_FAIL
  unset VPSKIT_TEST_SYSTEMD_AVAILABLE
  unset VPSKIT_TEST_SERVICE_EXISTS
  unset VPSKIT_TEST_SERVICE_ACTIVE
  unset VPSKIT_TEST_UFW_AVAILABLE
  unset VPSKIT_TEST_UFW_STATUS
  unset VPSKIT_TEST_SSHD_CONFIG_PATH
  unset VPSKIT_TEST_COMMAND_LOG
  unset VPSKIT_TEST_ROOT_DIR
  unset VPSKIT_TEST_PUBLIC_IP
  unset VPSKIT_TEST_UUID
  unset VPSKIT_TEST_X25519_OUTPUT
  unset VPSKIT_TEST_SHORT_ID
  unset VPSKIT_TEST_XRAY_BIN
  unset VPSKIT_TEST_FAIL_AFTER_CONFIG
  unset VPSKIT_MANAGED_USER
  unset VPSKIT_SSH_PORT
  unset VPSKIT_XRAY_PORT
  unset VPSKIT_XRAY_CONFIG_PATH
  unset VPSKIT_XRAY_TEMPLATE_PATH
  unset VPSKIT_SUBSCRIPTION_FILE
  unset VPSKIT_SUBSCRIPTION_DIR
  unset VPSKIT_REALITY_SERVER_NAME
  unset VPSKIT_REALITY_DEST
  unset VPSKIT_TROJAN_DOMAIN
  unset VPSKIT_PUBLIC_IPV4
  unset VPSKIT_HYSTERIA2_PORT
  unset VPSKIT_HYSTERIA2_MASQUERADE_HOST
  unset VPSKIT_LOCK_PATH
  unset VPSKIT_LOCK_METADATA_PATH
  unset VPSKIT_LOCK_FD
  unset VPSKIT_ROLLBACK_STACK
  unset VPSKIT_TRANSACTION_ACTIVE
  unset VPSKIT_SAFETY_ENABLE_TRAPS
}
