#!/usr/bin/env bash

set -euo pipefail

PROJECT_ROOT="$(git -C "${BATS_TEST_DIRNAME}" rev-parse --show-toplevel)"

load_core() {
  # shellcheck disable=SC1091
  source "${PROJECT_ROOT}/vpskit/core/common.sh"
  # shellcheck disable=SC1090
  source "${PROJECT_ROOT}/vpskit/core/$1"
}

reset_vpskit_test_env() {
  unset VPSKIT_DRY_RUN
  unset VPSKIT_DRY_RUN_MUTATION_FILE
  unset VPSKIT_TEST_MODE
  unset VPSKIT_TEST_EUID
  unset VPSKIT_TEST_OS_ID
  unset VPSKIT_TEST_OS_VERSION_ID
  unset VPSKIT_TEST_OS_VERSION_CODENAME
  unset VPSKIT_TEST_PORT_IN_USE
  unset VPSKIT_TEST_TCP_PORT_IN_USE
  unset VPSKIT_TEST_UDP_PORT_IN_USE
  unset VPSKIT_TEST_DNS_HEALTH_RESULT
  unset VPSKIT_TEST_DNS_HEALTH_FAIL
  unset VPSKIT_TEST_DNS_HEALTH_MISSING_TOOL
  unset VPSKIT_TEST_SYSTEMD_AVAILABLE
  unset VPSKIT_TEST_SERVICE_EXISTS
  unset VPSKIT_TEST_SERVICE_ACTIVE
  unset VPSKIT_TEST_UFW_AVAILABLE
  unset VPSKIT_TEST_UFW_STATUS
  unset VPSKIT_TEST_TCP_443_OWNER
  unset VPSKIT_TEST_TCP_8443_OWNER
  unset VPSKIT_TEST_TCP_8443_OWNER_AFTER_RESTART
  unset VPSKIT_TEST_TCP_8443_LISTENERS
  unset VPSKIT_TEST_SSHD_CONFIG_PATH
  unset VPSKIT_TEST_SSHD_CONFIG_DIR
  unset VPSKIT_TEST_SSHD_T_OUTPUT
  unset VPSKIT_TEST_SSHD_LISTENERS
  unset VPSKIT_TEST_AUTHORIZED_KEYS_SOURCE
  unset VPSKIT_TEST_AUTHORIZED_KEYS_VALID
  unset VPSKIT_TEST_MANAGED_USER_EXISTS
  unset VPSKIT_TEST_MANAGED_USER_GROUPS
  unset VPSKIT_TEST_SSH_DIR_OWNER
  unset VPSKIT_TEST_AUTHORIZED_KEYS_OWNER
  unset VPSKIT_TEST_MISSING_COMMANDS
  unset VPSKIT_TEST_COMMAND_LOG
  unset VPSKIT_TEST_ROOT_DIR
  unset VPSKIT_TEST_PUBLIC_IP
  unset VPSKIT_TEST_UUID
  unset VPSKIT_TEST_X25519_OUTPUT
  unset VPSKIT_TEST_SHORT_ID
  unset VPSKIT_TEST_XRAY_BIN
  unset VPSKIT_TEST_TROJAN_PASSWORD
  unset VPSKIT_TEST_HYSTERIA2_PASSWORD
  unset VPSKIT_TEST_HYSTERIA2_PIN_SHA256
  unset VPSKIT_TEST_UDP_443_OWNER
  unset VPSKIT_TEST_UDP_443_LISTENERS
  unset VPSKIT_TEST_XRAY_SERVICE_EXISTS
  unset VPSKIT_TEST_XRAY_SERVICE_ACTIVE
  unset VPSKIT_TEST_XRAY_SERVICE_ENABLED
  unset VPSKIT_TEST_FAIL_AFTER_CONFIG
  unset VPSKIT_TEST_FAIL_AFTER_SERVICE
  unset VPSKIT_XRAY_FORCE_OVERWRITE
  unset VPSKIT_CLIENT_NAME
  unset VPSKIT_AUTHORIZED_KEY
  unset VPSKIT_AUTHORIZED_KEY_FILE
  unset VPSKIT_SERVER_IP
  unset VPSKIT_TROJAN_PASSWORD
  unset VPSKIT_TROJAN_SERVER
  unset VPSKIT_TROJAN_SNI
  unset VPSKIT_TROJAN_ENV_FILE
  unset VPSKIT_TROJAN_SUBSCRIPTION_FILE
  unset VPSKIT_TROJAN_CONFIG_DIR
  unset VPSKIT_TROJAN_PORT
  unset VPSKIT_MANAGED_USER
  unset VPSKIT_SSH_PORT
  unset VPSKIT_XRAY_PORT
  unset VPSKIT_XRAY_CONFIG_PATH
  unset VPSKIT_XRAY_TEMPLATE_PATH
  unset VPSKIT_SUBSCRIPTION_FILE
  unset VPSKIT_SUBSCRIPTION_DIR
  unset VPSKIT_REALITY_SERVER_NAME
  unset VPSKIT_REALITY_DEST
  unset VPSKIT_TROJAN_DOMAIN
  unset VPSKIT_PUBLIC_IPV4
  unset VPSKIT_HYSTERIA2_PORT
  unset VPSKIT_HYSTERIA2_MASQUERADE_HOST
  unset VPSKIT_HYSTERIA2_BIN_PATH
  unset VPSKIT_HYSTERIA2_SERVICE_NAME
  unset VPSKIT_HYSTERIA2_SERVICE_UNIT_NAME
  unset VPSKIT_HYSTERIA2_CONFIG_DIR
  unset VPSKIT_HYSTERIA2_METADATA_FILE
  unset VPSKIT_HYSTERIA2_SUBSCRIPTION_FILE
  unset VPSKIT_HYSTERIA2_INSTALL_COMMAND
  unset VPSKIT_HYSTERIA2_RELEASE_TAG
  unset VPSKIT_HYSTERIA2_RELEASE_ASSET
  unset VPSKIT_HYSTERIA2_ARCH
  unset VPSKIT_LOCK_PATH
  unset VPSKIT_LOCK_METADATA_PATH
  unset VPSKIT_LOCK_FD
  unset VPSKIT_ROLLBACK_STACK
  unset VPSKIT_TRANSACTION_ACTIVE
  unset VPSKIT_SAFETY_ENABLE_TRAPS
}
